name: Arm GCC ArchLinux

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Init
        run: |
          pacman -Syu --noconfirm \
            git \
            make \
            cmake \
            ninja \
            arm-none-eabi-gcc \
            arm-none-eabi-newlib

      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake --preset Debug
          cmake --preset Release
          cmake --build --preset Debug
          cmake --build --preset Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stm32-${{ github.run_id }}
          path: |
            build/Debug/*.elf
            build/Debug/*.map
            build/Release/*.elf
            build/Release/*.map
          retention-days: 7
