name: Arm GCC Ubuntu

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Init
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi cmake ninja-build

      - name: Build
        run: |
          cmake --preset Debug
          cmake --preset Release
          cmake --build --preset Debug
          cmake --build --preset Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: arm-${{ github.run_id }}
          path: |
            build/**/*.elf
            build/**/*.map
          retention-days: 7


